### ISSUE TITLE
[Bug]: Graphic bug with Mekanism cables

### ISSUE THREAD

**Issue by hodo1962** [terrarium-earth/Ad-Astra#134]
### Bug Description

Mekanism cables were not shown correctly when Ad Astra is installed.
![2023-01-11_11 36 12](https://user-images.githubusercontent.com/69686049/211788411-536cfb50-a54b-40a7-a36d-f690c1d583ce.png)

Without Ad Astra everything looks ok.
![2023-01-11_11 49 09](https://user-images.githubusercontent.com/69686049/211788710-1fd5ba2b-8590-4358-8233-9ed1cf066023.png)

### How to Reproduce?

1. Deactivated Ad Astra - normal Mekanism cables
2. Activated Ad Astra - Mekanism cables were not shown correctly

### Version

1.12.1

### Mod Loader Version

1.19.2 - 43.2.0

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
do you have optifine, rubidium, or oculus?

**Comment by hodo1962** [comment]
I have Rubidium.

**Comment by AlexNijjar** [comment]
try without rubidium

**Comment by hodo1962** [comment]
I've installed Optifine. No more graphic errors. 
Now i can't play IC2 classic cause it doesn't work with Optifine. 
I've decided to drop IC2 : )

**Comment by AlexNijjar** [comment]
you shouldn’t be using optifine either for modern versions of mc. it’s an absolute pain for mod devs as you end up dealing with weird graphical issues like and the mod dev can’t diagnose it because optifine is closed-source. in many cases, the performance benefit is absent and in some cases worse than without it.
