### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Paxx3** [terrarium-earth/Ad-Astra#197]
### Bug Description

Hello, There is no recipe for:

Reinforced door
Steel sliding door

And when i place a normal torch on moon, it extinguishes but still produces light.

On moon, when the night comes, even if we sleep like 10 times, the sun dosen't come. Is this a bug or a feature? If normal, it should be on Astrodux

Can you please tell me the mods that is incompatable with Ad Astra? Thank you.

A bug with RARE ICE mod: When you place water on moon it freezes but when you put any item to the ice it becomes a rare ice block. After that when you break the ice, i do not know how but water comes without freezing. Like nether bug with water.

### Version

1.19.2

### Mod Loader Version

1.19.2

### Mod Loader

Fabric

### Logs or additional context

https://paste.atlauncher.com/view/714a8450-e443-4978-978b-53d6c6a77ff9

**Comment by Paxx3** [comment]
There is also no recipe for Rover

**Comment by AlexNijjar** [comment]
<img width="365" alt="Screenshot 2023-03-02 at 11 23 04 AM" src="https://user-images.githubusercontent.com/61668546/222504526-94d25a29-de4c-4098-9641-c07e1659a965.png">
<img width="356" alt="Screenshot 2023-03-02 at 11 23 18 AM" src="https://user-images.githubusercontent.com/61668546/222504579-92d92ed0-0844-4cdb-83cd-845ccd33185b.png">
<img width="360" alt="Screenshot 2023-03-02 at 11 23 34 AM" src="https://user-images.githubusercontent.com/61668546/222504637-239fc9d6-4848-4d1f-95fa-5eeb3772659c.png">
maybe another mod you have is breaking them?


torch issue will be fixed in the next update
pretty sure the sleep thing is a Minecraft bug
Optifine, Minecraft transit railway, immersive portals
looks like a rare ice issue?
