### ISSUE TITLE
[Feature Request]: Redstone-only sliding doors!

### ISSUE THREAD

**Issue by DABLONKIE** [terrarium-earth/Ad-Astra#219]
### Is your feature request related to a problem?

I'm trying to make a player sensor activated 3x3 door and accidentally clicking on it and opening it is annoying.

### Solution(s)

Add redstone-only variants of the sliding 3x3 doors.

### Describe alternatives you've considered

I haven't found any alternatives yet.

### Mod Version

1.19.2

### Mod Loader Version

43.2.6

### Mod Loader

Forge

**Comment by PeaceIsBliss** [comment]
Had this exact same thought today. Also increasing the redstone activation block to a 3x1 region under door. Also allow redstone 'toggle', instead of hand only shutting door. The active redstone Open/Shut mechanism is great, but should be able to reset it with a pulse (from open state). Also possibly comparator compatibility.

**Comment by zyxkad** [comment]
You can use create mod to impl a version, but not the best way

**Comment by AlexNijjar** [comment]
Added in 1.15.7. You can shift-right click it with a wrench to lock it and unlock it
