### ISSUE TITLE
[Bug]: Occasional Server Crash

### ISSUE THREAD

**Issue by Saereth** [terrarium-earth/Ad-Astra#266]
### Bug Description

We are getting some occasional server crashes by users showing up in our Auxilium reporting within FTB Skies. It appears to be related to ad astra/resourceful config and is not consistently reproducible. We do have the logs however.

### How to Reproduce?

Launch a server with FTB Skies 1.0.1 using the server files on the FTB App launcher
Most of the time it launches fine, occasionally it will crash

### Expected Behavior

Consistently not crashing

### Version

ad_astra-forge-1.19.2-1.12.6

### Mod Loader Version

Forge 1.19.2 - 43.2.6

### Mod Loader

Forge

### Logs or additional context

https://gist.github.com/JustAnotherGhostName/881c43ef02b7e4d9f60c4ef843cf18e1

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
Are there any mods in the pack that change how Resource Locations work because the code for this is literally this

pesudo code

```
channelMap = {}

channel = registerChannel() { channelMap.add(this) }

channel.registerPacket() {
 if (!channelMap.contains(this)) throw
 }
 ```
 so it makes it very hard for this to make sense without it failing to look up the channel list, because the internals require the channel to exist and for a channel to exist it has to have been put into that map that it looks up.
 
 Also have you had this issue with other mods because I see that a few mods in the pack also use the same networking system because its part of Resourceful Lib?

**Comment by ThatGravyBoat** [comment]
Ive uploaded a version that makes the error now print out the registered channels when it runs into this situation this should allow for me to find out whats causing the issue

**Comment by Saereth** [comment]
ok I've updated the mod and pushing it now for a pack update. the only resource location mod might be kubejs, but thats all I can think of

**Comment by AlexNijjar** [comment]
https://github.com/Team-Resourceful/ResourcefulLib/issues/4#issuecomment-1631659638
