### ISSUE TITLE
[Bug]: Distributer won't check the area that already filled oxygen by other distributer

### ISSUE THREAD

**Issue by zyxkad** [terrarium-earth/Ad-Astra#275]
### Bug Description

I have a huge space station, and I used multiple oxygen distributer to fill it.
But the distributer will report error like block > 2000, and when I show the oxygen fill range, I saw multiple distributer filled same area.
The water will be froze too, I don't understand.

### How to Reproduce?

1. Build a 10 * 10 * 30 passage.
2. Place distributer at each end of the passage, give it water and energy.
3. It will warn you the area is larger than 2000, and you will see the bubble filled some duplicate area.
4. Place water near the distributer, even bubbles around the water, it will frozen

### Expected Behavior

The distributer won't fill area that already filled by other distributer, and the water shouldn't froze with air around it

### Version

1.12.6

### Mod Loader Version

1.19.2 - 43.2.4

### Mod Loader

Forge

### Logs or additional context

P.S.: I didn't find the FAQ page

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [ ] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
it's not really possible for the oxygen distributors to check other oxygen distributors' oxygen as that would be highly efficient. you should be able to just place multiple down around the space station and ignore the warning.

**Comment by zyxkad** [comment]
@AlexNijjar No, I cannot ignore the warning, player cannot breath when the warning appeared, and water block will be freeze even just next to the distributer

**Comment by zyxkad** [comment]
What about make oxygen distributors as a multi-block structure, you can stack them, will it be more efficient and easy?

**Comment by AlexNijjar** [comment]
do you have a video of this occurring? because the distributor should be able to still protect players and water, even when it's reached its limit, it just won't be able to cover the entire area of the space station.

There's also a performance penalty when increasing the amount of distributed blocks so with something like a multiblock, someone could easily lag the server If that limit is increased. In addition, the oxygen distributor model was redesigned and in the new model, it doesn't make sense for it to be used as a multi block.

For your specific case, you can just increase the limit in the config from 2000 to whatever the size of your space station is.
