### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MarcusLogothetis** [terrarium-earth/Ad-Astra#317]
### Bug Description

When leaving Glacio with a tier 1 rocket you can only travel to Earth. This bug also occurs when leaving from other planets.

### How to Reproduce?

1. Go to Glacio
2. Use a tier 1 rocket and leave Glacio

### Expected Behavior

I would expect that when leaving Glacio with a tier 1 rocket, you can only go to Venus and with a tier 2 you could go to Mercury and so on.

### Version

1.12.6

### Mod Loader Version

1.19.2 - 43.2.14

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
this is kind of an intended feature. the tier of your rocket dictates what tier of planet you can land on so since earth requires a tier 1 rocket, you can go there with a tier 1 rocket from anywhere. logically it doesn't really make much sense and it'll probably be changed eventually but for now this is expected.
