### ISSUE TITLE
[Feature Request]: Ability to adjust suit oxygen hud

### ISSUE THREAD

**Issue by MLMII** [terrarium-earth/Ad-Astra#402]
### Is your feature request related to a problem?

The suit oxygen hud covers upper left corner of the screen which is where my minimap is located. 

### Solution(s)

Adding a config option to adjust the hud as well as an option to make the oxygen tanks smaller would be really nice.

### Mod Version

ad_astra-fabric-1.20.1-1.15.4

### Mod Loader Version

0.21.1-1.20.1

### Mod Loader

Quilt

### Additional context

Thank you for your time for this fun mod.

**Comment by AlexNijjar** [comment]
This already exists in the config.
<img width="235" alt="Screenshot 2023-11-07 at 1 01 46 PM" src="https://github.com/terrarium-earth/Ad-Astra/assets/61668546/fb125616-e38a-4172-a449-ba30f396037d">

**Comment by MLMII** [comment]
Yeah, I just discovered that and was coming to delete the issue.  Sorry.

**Comment by Nova-Katt** [comment]
I would like to add to that, that it would be nice if this was configurable ingame, without having to close down the game, edit a config file, start the game up (which takes a while if you're running lots of mods), load the map, and then see if you moved it to a good position, otherwise... close down the game, edit the config file, start up the game, load the map... all again.
So if it was possible to move the hug around while ingame, that would be an amazing addition. :)

**Comment by ThatGravyBoat** [comment]
> I would like to add to that, that it would be nice if this was configurable ingame, without having to close down the game, edit a config file, start the game up (which takes a while if you're running lots of mods), load the map, and then see if you moved it to a good position, otherwise... close down the game, edit the config file, start up the game, load the map... all again.
> 
> So if it was possible to move the hug around while ingame, that would be an amazing addition. :)

You can edit it in game, just find the config button in the mod list/mod menu you'll find the options in there

**Comment by Nova-Katt** [comment]
Ooooh I checked the config like 5 times before and didn't see it, but now I saw the Client Config Button! <3
Thank you! :D
