### ISSUE TITLE
[Bug][NeoForge]: star-map does not work 

### ISSUE THREAD

**Issue by canitzp** [terrarium-earth/Ad-Astra#466]
### Bug Description

I'm testing the latest AdAstra version (1.16.3) with NeoForge and I ahve noticed, that the star-map does not work. It is just empty.
I don't have any additional datapacks installed.
I also tested several versions of NeoForge, but nothing changed.

![2024-02-09_13 52 28](https://github.com/terrarium-earth/Ad-Astra/assets/12819060/97b74e30-9ade-4b59-ac13-1dfcc36c9b54)

### How to Reproduce?

1. Install AdAstra with NeoForge on Minecraft 1.20.4
2. Create a new world
3. Run command "/adastra planets"
4. View the non-existent planets

### Version

1.16.3

### Mod Loader Version

1.20.4 - 20.4.146-beta

### Mod Loader

NeoForge

### Logs or additional context

There is no error in log

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by canitzp** [comment]
So I have investigated this problem a bit. Turns out the "ClientboundSyncPlanetsPacket" does not work properly. The encode (https://github.com/terrarium-earth/Ad-Astra/blob/bd7b25ad03074c7a2b18ba82eafb736b20c0f61b/common/src/main/java/earth/terrarium/adastra/common/network/messages/ClientboundSyncPlanetsPacket.java#L40) and decode (https://github.com/terrarium-earth/Ad-Astra/blob/bd7b25ad03074c7a2b18ba82eafb736b20c0f61b/common/src/main/java/earth/terrarium/adastra/common/network/messages/ClientboundSyncPlanetsPacket.java#L41) are never called. Since I don't know, how the ResourcefulLib networking works, I can't investigate further.

**Comment by ThatGravyBoat** [comment]
> So I have investigated this problem a bit. Turns out the "ClientboundSyncPlanetsPacket" does not work properly. The encode (
> 
> https://github.com/terrarium-earth/Ad-Astra/blob/bd7b25ad03074c7a2b18ba82eafb736b20c0f61b/common/src/main/java/earth/terrarium/adastra/common/network/messages/ClientboundSyncPlanetsPacket.java#L40
> ) and decode (
> 
> https://github.com/terrarium-earth/Ad-Astra/blob/bd7b25ad03074c7a2b18ba82eafb736b20c0f61b/common/src/main/java/earth/terrarium/adastra/common/network/messages/ClientboundSyncPlanetsPacket.java#L41
> ) are never called. Since I don't know, how the ResourcefulLib networking works, I can't investigate further.

The reason they are never called is because Encode and Decode dont get all in singleplayer this is to optimize the games performance as to not do unneeded operations when there is no actual network all it does is send the packet object to the handle method right away.

**Comment by AlexNijjar** [comment]
I was able to reproduce it so I'll check it out

**Comment by AlexNijjar** [comment]
problem was that since there were no encoding and decoding, ie the map reference was sent directly instead of creating a copy, it was clearing itself and then setting itself to itself. Fixed it by just creating a copy of the map and then clearing it and then setting the v

https://github.com/terrarium-earth/Ad-Astra/blob/6f3d2b3c3c50c3245af8f8befdd14e7187dd645c/common/src/main/java/earth/terrarium/adastra/common/planets/AdAstraData.java#L91

**Comment by AlexNijjar** [comment]
problem was that since there were no encoding and decoding, ie the map reference was sent directly instead of creating a copy, it was clearing itself and then setting itself to itself. Fixed it by just creating a copy of the map before clearing the original and then setting the original to the copy. It was working on fabric because I guess fabric still encodes and decodes?

https://github.com/terrarium-earth/Ad-Astra/blob/6f3d2b3c3c50c3245af8f8befdd14e7187dd645c/common/src/main/java/earth/terrarium/adastra/common/planets/AdAstraData.java#L91-L93
